language: node_js

node_js:
  - 5.8
  - 5.9
  - 5.10

before_deploy:
  - npm run build

sudo: false

deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: WgEqtKsIHAWQ6SdzEg6P9MLVABMiowPLZ9Xb7a37Dbqp7L8UFPfZeTVvUXXKGs8H+VNFrsk+qImvmhQqco9FrzaxLgvF6RlccPc1+jjGMbYKUU8IGwltYd/YCpriew+GKzAwSmLGyLknhtkeRJvgYdWlFSwkTDoNuPY5E7bbLqnVdGPNPBbn2nyVkcaxepngJaSZFeZdEnnXbMrUGFtVp5faN/fn08mLznz5Dj+f23KlC9MzsfwxLKq4KjAaZoTIM8R2wXXwisDBc6NN7/LK6nv9Eus4AcgCvGaLZp2FZHAytEMqhvthi6EzVcV3LBZPG6UXKXjrwgSY3a3gykhOoq3tZtSX4FVdEKWgDB7WTtjSQFIP7oWrmfypMiGdPnTv/YKZ16kEPjs6gQUEKuzumwu3UJTQuR8Y2xcbrpCQn1w2xis6rqU+TP3S3lkPJg4bdL3SbSVUQVenH5IKZMQG8DZB557SVE0gg7x4gNp+9mAAk5xhCW8YviyYCwqER9ehdE53yLSUQy3zvn2ZVp4c0xfTcnZEq2Zu2luaBlV8nMKcAeyqbxwa670zlCfOHm8F1pTKWkezbrhC1K925otMLDjuzgksmIatzXGcZ8Ox4hyy1/ShqSpTBdc+bRu6AchRbuCYT0aPEQdfJoXq34JPqqQTb2H7BdxdTBusdQcQ3hA=
  app: react-standalone
  on:
    repo: Wildhoney/Standalone
